name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        version: ["5.6", "7.0", "7.2", "7.3", "7.4", "8.0", "8.2"]
      fail-fast: false

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ${{matrix.version}} -t mcserep/php:${{matrix.version}}
    - name: Login to Docker Hub
      if: ${{ github.repository == 'mcserep/docker-php' && github.ref_name == 'master' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Upload the Docker image
      if: ${{ github.repository == 'mcserep/docker-php' && github.ref_name == 'master' }}
      run: docker push mcserep/php:${{matrix.version}}
